path: ./datasets
train: train/
val: train/
test: test/

names:
  0: 行驶证
  1: 行驶证背面
  2: 驾驶证
  3: 驾驶证背面
  4: 身份证
  5: 身份证背面
  6: 护照
  7: 港澳台通行证
  8: 台湾回乡证
  9: 台湾回乡证背面
  10: 澳门居民身份证
  11: 军官证
  12: 港澳居民来往内地通行证
  13: 广东省居住证
